# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 15:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('year', models.IntegerField(default=2018, primary_key=True, serialize=False)),
                ('inflation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('proj_costing_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Preparation'), ('R', 'Review'), ('F', 'Funded'), ('X', 'Rejected')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_from', models.DateTimeField()),
                ('employed_until', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSEAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=1)),
                ('grade_point', models.IntegerField(default=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('increments', models.BooleanField(default=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rse.FinancialYear')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGradeChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rse.RSE')),
                ('salary_band', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rse.SalaryBand')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rse.Project')),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overheads', models.CharField(choices=[('N', 'None'), ('U', 'UKRI'), ('E', 'EU')], default='N', max_length=1)),
            ],
            bases=('rse.project',),
        ),
        migrations.CreateModel(
            name='ServiceProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rse.Project')),
                ('days', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            bases=('rse.project',),
        ),
        migrations.AddField(
            model_name='rseallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.Project'),
        ),
        migrations.AddField(
            model_name='rseallocation',
            name='rse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.RSE'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rse.Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
