# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-02 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('funder_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('academic_contact', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('percentage', rse.models.PercentageField()),
                ('overheads', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('P', 'Preperation'), ('R', 'Review'), ('F', 'Funded'), ('X', 'Rejected')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rse.Client')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_employment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSEAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', rse.models.PercentageField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.Project')),
                ('rse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.RSE')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=1)),
                ('grade_point', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='rse',
            name='salary_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rse.SalaryBand'),
        ),
        migrations.AddField(
            model_name='rse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
