# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 15:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rseallocation',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
