# Generated by Django 2.2.3 on 2019-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
