# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rse',
            name='employed_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rse',
            name='employed_until',
            field=models.DateField(),
        ),
    ]
