# Generated by Django 2.2.3 on 2019-11-24 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0002_auto_20191122_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='rseallocation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rseallocation',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
