# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rse', '0002_auto_20190705_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_rse.project_set+', to='contenttypes.ContentType'),
        ),
    ]
