# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0003_auto_20180920_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2018)),
                ('inflation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGradeChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='rse',
            name='salary_band',
        ),
        migrations.AddField(
            model_name='salaryband',
            name='increments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarygradechange',
            name='rse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rse.SalaryBand'),
        ),
        migrations.AddField(
            model_name='salaryband',
            name='year',
            field=models.ForeignKey(default=2018, on_delete=django.db.models.deletion.DO_NOTHING, to='rse.FinancialYear'),
            preserve_default=False,
        ),
    ]
