# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0004_auto_20180930_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='id',
        ),
        migrations.AddField(
            model_name='salaryband',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='year',
            field=models.IntegerField(default=2018, primary_key=True, serialize=False),
        ),
    ]
