# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0004_auto_20190715_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedproject',
            name='salary_band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rse.SalaryBand'),
            preserve_default=False,
        ),
    ]
