# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0006_auto_20180930_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rseallocation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rseallocation',
            name='start',
            field=models.DateField(),
        ),
    ]
