# Generated by Django 3.2.19 on 2023-07-26 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0007_auto_20230724_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directlyincurredproject',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
