# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0008_auto_20180930_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funder_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
