# Generated by Django 3.2.19 on 2023-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0008_alter_directlyincurredproject_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='overheads_rate',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=8),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='service_day_rate',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=8),
        ),
    ]
