# Generated by Django 3.2.19 on 2023-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0009_auto_20230728_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproject',
            name='days',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
    ]
