# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0009_auto_20190607_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('P', 'Preparation'), ('R', 'Review'), ('F', 'Funded'), ('X', 'Rejected')], max_length=1),
        ),
    ]
