# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rse', '0010_auto_20190607_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='funder_id',
            new_name='proj_costing_id',
        ),
    ]
