import os

DEV_CONTAINER = os.getenv('DEV_CONTAINER')

MIN_PROJECT_PERCENTAGE = 5
MAX_PROJECT_PERCENTAGE = 120
PERCENTAGE_STEP = 5

INACTIVE_USER_USERNAME = 'user_inactive'
INACTIVE_USER_FIRST_NAME = 'Inactive'
INACTIVE_USER_LAST_NAME = 'Test'