# Generated by Django 3.0 on 2019-12-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rse', '0006_remove_rse_employed_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.RSE')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.Project')),
            ],
        ),
    ]
